services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: always
    ports:
      - "4321:80"
    networks:
      - webnet-portfolio
    env_file:
      - ./.env

networks:
  webnet-portfolio:
    driver: bridge
 
